name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main 
  workflow_dispatch:  # Allows manual trigger from GitHub UI

env:
  PROJECT_ID: pocketbase-454721
  REGION: australia-southeast1
  SERVICE_NAME: expense-tracker

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write  # Needed for auth with Google Cloud
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          token_format: 'access_token'
        
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
          
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and Push Container
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/expense-tracker/${{ env.SERVICE_NAME }}:${{ github.sha }}
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/expense-tracker/${{ env.SERVICE_NAME }}:latest
        
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/expense-tracker/${{ env.SERVICE_NAME }}:${{ github.sha }}
        
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }} 